#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-TH.data
Version  : 1.0
Release  : 2
URL      : https://cran.r-project.org/src/contrib/TH.data_1.0-7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/TH.data_1.0-7.tar.gz
Summary  : TH's Data Archive
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : clr-R-helpers R-plyr

%description
**********************************************************************
*  Reproducibility Information for
*  Spatio-Phylogenetic Multi-Species Distribution Models
*  by A. Kaldhusdal, R. Brandl, J. Mueller, L. Moest and T. Hothorn
**********************************************************************

%prep
%setup -q -c -n TH.data

%build

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library TH.data
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library TH.data


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/TH.data/